#!/bin/bash
#
# This is a Nagios plugin used to check the queries per seconds of a log file (or something similar).
#
# The script "linespersec" is required.
# It's available at https://github.com/samyboy/linespersec
#
#
# Author: Samuel Krieg <samuel.krieg+github@gmail.com>
#
#

set -e

LINESPERSEC="linespersec"

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3

# Default exit code
EXIT_CODE=$STATE_OK

SERVICE_NAME="check_qps"
VERBOSITY_LEVEL=0

show_version(){
  cat <<EOF
check_qps v1
Samuel Krieg <samuel.krieg@gmail.com>

EOF
}

show_usage(){
  show_version
  cat <<EOF
Nagios plugin: check the queries per second based on a log file
The script assumes one line is one query.

Usage: check_qps -f <file> [-w <qps>] [-c <qps>] [-v]

Options:
 -h
    Print detailed help screen
 -V
    Print version information
 -f file
    The file to check
 -w INTEGER
    Exit with WARNING status if queries/sec is greater than INTEGER
 -c INTEGER
    Exit with CRITICAL status if queries/sec is greater than INTEGER
 -v 
    Verbose output
EOF
}

#
# verbose output
#
echov (){
  [ "$VERBOSITY_LEVEL" -ge "1" ] && echo $@
}

#
# Command arguments handling
# FIXME: handle --help and --version

# script invoked with no command line args: exit with error
if [ $# -eq "0" ]
then
  show_usage
  exit $STATE_UNKNOWN
fi  

#
# parse arguments
#
while getopts ":hvVf:c:w:" OPTION
  do
  case "$OPTION" in
    "V")
      show_version
      exit $STATE_OK
      ;;
    "h")
      show_usage
      exit $STATE_OK
      ;;
    "w")
      WARNING_VALUE=$OPTARG
      ;;
    "c")
      CRITICAL_VALUE=$OPTARG
      ;;
    "f")
      FILE=$OPTARG
      ;;
    "v")
      VERBOSITY_LEVEL=$(($VERBOSITY_LEVEL + 1))
      echo "VERBOSITY_LEVEL = $VERBOSITY_LEVEL"
      ;;
    "?")
      echo "Unknown option $OPTARG"
      exit $STATE_UNKNOWN
      ;;
    ":")
      echo "No argument value for option $OPTARG"
      exit $STATE_UNKNOWN
      ;;
    *)
       # Should not occur
      echo "Unknown error while processing options"
      exit $STATE_UNKNOWN
      ;;
  esac
done

#
# Check arguments validity
#
if [ -z "$FILE" ]; then
  echo "Missing arguments"
  show_usage
  exit $STATE_UNKNOWN
fi

# check if file exists
if [ ! -f "$FILE" ]; then
    echo "\"$FILE\": no such file"
    exit $STATE_UNKNOWN
fi

#
# Main program
#

value=$( $LINESPERSEC $FILE )
if [ -z "$value" ]; then
    value=0
fi

intValue=${value/\.*}

NAGIOS_STATUS="OK"

if [ -n "$CRITICAL_VALUE" ] && [ "$intValue" -ge "$CRITICAL_VALUE" ]; then
    # this is critical
    echo "$intValue -ge $CRITICAL_VALUE"
    NAGIOS_STATUS="CRITICAL"
    EXIT_CODE=$STATE_CRITICAL
fi

if [ -n "$WARNING_VALUE" ] && [ "$intValue" -ge "$WARNING_VALUE" ]; then
    echo "$intValue -ge $WARNING_VALUE"
    NAGIOS_STATUS="WARNING"
    # this is warning
    EXIT_CODE=$STATE_WARNING
fi


echo "$NAGIOS_STATUS | qps=${value};${WARNING_VALUE};${CRITICAL_VALUE}"
#
# Exit status
#
exit $EXIT_CODE

